#travis file to build container and push to docker hub
dist: xenial
services:
  - docker
before_install:
  - docker build -t stanleyeze/node-loadtest:process.env.TRAVIS_BUILD_ID .

script:
  - docker run stanleyeze/node-loadtest:process.env.TRAVIS_BUILD_ID npm run test -- --coverage

after_success:
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  - docker push stanleyeze/node-loadtest
