dist: xenial
services:
  - docker
before_install:
  - docker build -t stanleyeze/node-loadtest-test -f Dockerfile.dev

script:
  - docker run stanleyeze/node-loadtest-test npm run test -- --coverage

after_success:
  - docker build -t stanleyeze/node-loadtest .
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  - docker push stanleyeze/node-loadtest
