#travis file to build container and push to docker hub
dist: xenial
services:
  - docker
before_install:
  #builds a test image/container
  #for running tests
  #in this case, I didn't include test in my solution
  #just for demonstration purpose
  - docker build -t stanleyeze/client -f ./client/Dockerfile.dev

script:
  #overides the start commad so as to run test
  #no test runs in this solution
  - docker run stanleyeze/node-loadtest npm run test -- --coverage

  #after successful test, etc..
after_success:
  #builds images
  - docker build -t stanleyeze/loadtest-client ./client
  - docker build -t stanleyeze/loadtest-backend ./backend
  - docker build -t stanleyeze/loadtest-nginx ./nginx

  #login to docker hub
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin

  #push images to docker hub
  - docker push stanleyeze/loadtest-client
  - docker push stanleyeze/loadtest-backend
  - docker push stanleyeze/loadtest-nginx
