version: "3"
services:
  backend:
    build:
      dockerfile: Dockerfile
      context: ./backend
    volumes:
      - /home/node_modules
      - ./backend:/home
  nginx:
    restart: always
    build:
      dockerfile: Dockerfile
      context: ./nginx
    ports:
      - "3000:80"
  client:
    build:
      dockerfile: Dockerfile
      context: ./client
    volumes:
      - /home/node_modules
      - ./client:/home
